import type { Metadata } from 'next'

export const metadata: Metadata = {
	title: 'Home',
	description: 'Generated by create next app',
}

export default function HomePage() {
	return <h1>HomePage</h1>
}
