import Home from '@/components/screens/home/Home'
import type { Metadata } from 'next'

export const metadata: Metadata = {
	title: 'Home',
	description: 'Generated by create next app',
}

export default function HomePage() {
	return <Home />
}
